server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://180.76.188.207:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Wangbeibei?2278
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.liamcoder.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true